version: '3'
services:
  api:
    container_name: blog_api
    build:
      context: api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=blog
      - DB_USER=root
      - DB_PASSWORD=dev_pass

  db:
    container_name: blog_db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev_pass
      - MYSQL_DATABASE=blog

  client:
    container_name: blog_client
    build:
        context: client
    volumes:
      - ./client:/var/www/client
    ports:
      - "3000:3000"