version: '3'
services:
  api:
    container_name: blog_api
    build:
      context: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: blog_db
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: blog
      MARIADB_USER: user
      MARIADB_USER_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: root
    networks: 
      - app

#  client:
#    container_name: blog_client
#    build:
#        context: client
#    volumes:
#      - ./client:/var/www/client
#    ports:
#      - "3000:3000"
#    networks:
#      - app

networks:
  app: